name: check

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - 'master'
      - 'main'
      - '*'
  pull_request:

jobs:
  drupal-9:
    runs-on: ubuntu-18.04
    steps:
      # To support the local tool `act` without their
      # recommended container image, we install the tools
      # directly on the build container running, and
      # perform a pre-run cleanup.
      #
      # For more information, see the act project.
      # - https://github.com/nektos/act
      -
        name: Clean-up
        run: rm -rf govcms-site || true
      -
        name: Setup project for testing.
        run: COMPOSER_MEMORY_LIMIT=-1 composer create-project govcms/govcms8-project govcms-site
      -
        name: Install upgrade_status
        run: cd govcms-site && composer require drupal/upgrade_status:*
      -
        name: Install drupal-check
        run: cd govcms-site && composer global require mglaman/drupal-check
      -
        name: Run Check
        run: cd govcms-site && composer why-not -t drupal/core:~9 || true
      -
        name: Run drupal-check
        run: cd govcms-site && drupal-check -ad .
      -
        name: Run Upgrade Status
        run: cd govcms-site && drush upgrade_status:analyze --all --ignore-contrib || true